### ISSUE TITLE
Expand-on-Hover tab bar is not styled

### ISSUE THREAD

**Issue by cswimr** [IAmJafeth/zen-browser#1]
Hi there! I really like this theme, but I noticed that the Expand-on-Hover tab bar is not styled like the rest of the theme. Figured I'd report it here, I'm pretty sure this issue should get transferred to the catppuccin repository in theory.

https://github.com/user-attachments/assets/a40250e2-02c7-474e-bf69-7a211443c15d

**Comment by IAmJafeth** [comment]
Hi @cswimr !

Thank you so much for your report and contribution, this should be fixed with latest commit 03bb6a03b13eff4a281a5ed6b93167e4fbfd5d77

Could you please update your userChrome.css with the latest available in the the repository and confirm if you are still facing the same issue?

Looking forward for your response.

**Comment by cswimr** [comment]
Can confirm that this issue is fixed, thanks!
